name: CoordinateOffset
version: "${version}"
main: com.jtprince.coordinateoffset.CoordinateOffset
api-version: "${apiVersion}"
depend: [ ProtocolLib ]
authors: [ jtprince, Cavallium ]
website: https://github.com/joshuaprince/CoordinateOffset
description: Configurably obfuscate players' coordinates.
permissions:
  coordinateoffset.bypass:
    description: Players with this permission will never have their coordinates offsetted.
  coordinateoffset.query:
    description: Allows you to use the /offset command, which tells you your current offset.
  coordinateoffset.query.others:
    description: Allows you to query other players' offsets with /offset <name>.
    children:
      coordinateoffset.query: true
  coordinateoffset.reload:
    description: Allows you to reload the plugin config with /offsetreload.
